version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Auth Module/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
