version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API Module/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
