version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Service Module/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
